# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('end_date', models.DateTimeField(verbose_name='end_date')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('current_target', models.IntegerField(blank=True)),
                ('signature', models.CharField(max_length=32)),
                ('kill_signature', models.CharField(max_length=32)),
                ('alive', models.BooleanField(default=True)),
                ('death_time', models.DateTimeField(blank=True, default='1920-02-02', verbose_name='death_time')),
                ('death_note', models.CharField(blank=True, max_length=2000)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
