# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-14 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_time', models.DateTimeField(blank=True, null=True, verbose_name='kill_time')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('signature', models.CharField(max_length=32)),
                ('kill_signature', models.CharField(max_length=32)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes')),
                ('alive', models.BooleanField(default=True)),
                ('death_time', models.DateTimeField(blank=True, null=True, verbose_name='death_time')),
                ('death_note', models.TextField(blank=True, null=True)),
                ('current_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kill',
            name='killer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killer', to='game.Player'),
        ),
        migrations.AddField(
            model_name='kill',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='game.Player'),
        ),
    ]
