# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='death_time',
            field=models.DateTimeField(blank=True, verbose_name='death_time'),
        ),
    ]
