# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='death_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='death_time'),
        ),
    ]
