# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170104_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
