# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170104_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
