# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='death_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
