# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170105_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='qr_code',
            new_name='qrcode',
        ),
    ]
